import { HospitalEntity } from "src/hospitals/entitiy/hospital.entity";

import { ScheduleEntity } from "src/schedule/entity/schedule.entity";
import { MediaEntity } from "src/media/entity";
import { Role } from "src/schedule/types/enum";

export interface SignUpUser {
  email: string;
  name: string;
  password: string;
  repeatPassword: string;
}

export interface BaseUser {
  id: number;
  email: string;
  name: string;
  password: string;
}

export interface DBuser extends BaseUser {
  password: string;
  role: Role[];
  isVerified: boolean;
  hashedRefreshToken: string;
  deletedAt: Date;
  isDeleted: boolean;
  autogeneratedPassword: boolean;
  resetPasswordToken: string;
  hospitalDoctor: HospitalEntity;
  hospitalAdmin: HospitalEntity;
  schedule: ScheduleEntity[];
  avatar: MediaEntity;
}
